CREATE TABLE `attachments` (
	`_original` blob,
	`threadKey` text NOT NULL,
	`messageId` text NOT NULL,
	`attachmentFbid` text,
	`filename` text,
	`filesize` integer,
	`hasMedia` integer,
	`isSharable` integer,
	`playableUrl` text,
	`playableUrlFallback` text,
	`playableUrlExpirationTimestampMs` integer,
	`playableUrlMimeType` text,
	`dashManifest` text,
	`previewUrl` text,
	`previewUrlFallback` text,
	`previewUrlExpirationTimestampMs` integer,
	`previewUrlMimeType` text,
	`miniPreview` text,
	`previewWidth` integer,
	`previewHeight` integer,
	`attributionAppId` text,
	`attributionAppName` text,
	`attributionAppIcon` text,
	`attributionAppIconFallback` text,
	`attributionAppIconUrlExpirationTimestampMs` integer,
	`localPlayableUrl` text,
	`playableDurationMs` integer,
	`attachmentIndex` integer,
	`accessibilitySummaryText` text,
	`isPreviewImage` integer,
	`originalFileHash` text,
	`attachmentType` text,
	`timestampMs` integer,
	`offlineAttachmentId` text,
	`hasXma` integer,
	`xmaLayoutType` text,
	`xmasTemplateType` text,
	`titleText` text,
	`subtitleText` text,
	`descriptionText` text,
	`sourceText` text,
	`faviconUrlExpirationTimestampMs` integer,
	`isBorderless` integer,
	`previewUrlLarge` text,
	`samplingFrequencyHz` integer,
	`waveformData` text,
	`authorityLevel` text,
	FOREIGN KEY (`threadKey`) REFERENCES `threads`(`threadKey`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`messageId`) REFERENCES `messages`(`messageId`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE `messages` (
	`_original` blob,
	`threadKey` text NOT NULL,
	`offlineThreadingId` text,
	`authorityLevel` integer,
	`timestampMs` integer,
	`messageId` text PRIMARY KEY NOT NULL,
	`senderId` text NOT NULL,
	`isAdminMessage` integer,
	`sendStatus` text,
	`text` text,
	`subscriptErrorMessage` text,
	`stickerId` text,
	`messageRenderingType` text,
	`isUnsent` integer,
	`unsentTimestampMs` integer,
	`mentionOffsets` text,
	`mentionLengths` text,
	`mentionIds` text,
	`mentionTypes` text,
	`replySourceId` text,
	`replySourceType` text,
	FOREIGN KEY (`threadKey`) REFERENCES `threads`(`threadKey`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE `participants` (
	`_original` blob,
	`threadKey` text NOT NULL,
	`userId` text NOT NULL,
	`readWatermarkTimestampMs` integer,
	`readActionTimestampMs` integer,
	`deliveredWatermarkTimestampMs` integer,
	`lastDeliveredActionTimestampMs` integer,
	`isAdmin` integer,
	FOREIGN KEY (`threadKey`) REFERENCES `threads`(`threadKey`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`userId`) REFERENCES `users`(`threadKey`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE `reactions` (
	`_original` blob,
	`threadKey` text,
	`timestampMs` integer,
	`messageId` text,
	`actorId` text,
	`reaction` text
);
--> statement-breakpoint
CREATE TABLE `threads` (
	`_original` blob,
	`threadKey` text PRIMARY KEY NOT NULL,
	`lastReadWatermarkTimestampMs` integer,
	`threadType` text,
	`folderName` text,
	`parentThreadKey` text,
	`lastActivityTimestampMs` integer,
	`snippet` text,
	`threadName` text,
	`threadPictureUrl` text,
	`needsAdminApprovalForNewParticipant` integer,
	`threadPictureUrlFallback` text,
	`removeWatermarkTimestampMs` integer,
	`muteExpireTimeMs` integer,
	`groupNotificationSettings` text,
	`isAdminSnippet` integer,
	`snippetSenderContactId` text,
	`snippetStringHash` text,
	`snippetStringArgument1` text,
	`snippetAttribution` text,
	`snippetAttributionStringHash` text,
	`disappearingSettingTtl` integer,
	`disappearingSettingUpdatedTs` integer,
	`disappearingSettingUpdatedBy` text,
	`cannotReplyReason` text,
	`customEmoji` text,
	`customEmojiImageUrl` text,
	`outgoingBubbleColor` text,
	`themeFbid` text
);
--> statement-breakpoint
CREATE TABLE `typing_indicators` (
	`_original` blob,
	`threadKey` text NOT NULL,
	`minTimestampMs` integer,
	`minMessageId` text,
	`maxTimestampMs` integer,
	`maxMessageId` text,
	`isLoadingBefore` integer,
	`isLoadingAfter` integer,
	`hasMoreBefore` integer,
	`hasMoreAfter` integer
);
--> statement-breakpoint
CREATE TABLE `users` (
	`_original` blob,
	`threadKey` text NOT NULL,
	`profilePictureUrl` text,
	`name` text,
	`username` text,
	FOREIGN KEY (`threadKey`) REFERENCES `threads`(`threadKey`) ON UPDATE no action ON DELETE no action
);
