CREATE TABLE `attachments` (
	`_original` text,
	`threadKey` text NOT NULL,
	`messageId` text NOT NULL,
	`attachmentFbid` text,
	`filename` text,
	`filesize` integer,
	`hasMedia` integer,
	`isSharable` integer,
	`playableUrl` text,
	`playableUrlFallback` text,
	`playableUrlExpirationTimestampMs` integer,
	`playableUrlMimeType` text,
	`dashManifest` text,
	`previewUrl` text,
	`previewUrlFallback` text,
	`previewUrlExpirationTimestampMs` integer,
	`previewUrlMimeType` text,
	`miniPreview` text,
	`previewWidth` integer,
	`previewHeight` integer,
	`attributionAppId` text,
	`attributionAppName` text,
	`attributionAppIcon` text,
	`attributionAppIconFallback` text,
	`attributionAppIconUrlExpirationTimestampMs` integer,
	`localPlayableUrl` text,
	`playableDurationMs` integer,
	`attachmentIndex` integer,
	`accessibilitySummaryText` text,
	`isPreviewImage` integer,
	`originalFileHash` text,
	`attachmentType` text,
	`timestampMs` integer,
	`offlineAttachmentId` text,
	`hasXma` integer,
	`xmaLayoutType` text,
	`xmasTemplateType` text,
	`titleText` text,
	`subtitleText` text,
	`descriptionText` text,
	`sourceText` text,
	`faviconUrlExpirationTimestampMs` integer,
	`isBorderless` integer,
	`previewUrlLarge` text,
	`samplingFrequencyHz` integer,
	`waveformData` text,
	`authorityLevel` text,
	FOREIGN KEY (`threadKey`) REFERENCES `threads`(`threadKey`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`messageId`) REFERENCES `messages`(`messageId`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE `messages` (
	`_original` text,
	`threadKey` text NOT NULL,
	`offlineThreadingId` text,
	`authorityLevel` integer,
	`timestampMs` integer,
	`messageId` text PRIMARY KEY NOT NULL,
	`senderId` text NOT NULL,
	`isAdminMessage` integer,
	`sendStatus` text,
	`sendStatusV2` text,
	`text` text,
	`subscriptErrorMessage` text,
	`stickerId` text,
	`messageRenderingType` text,
	`isUnsent` integer,
	`unsentTimestampMs` integer,
	`mentionOffsets` text,
	`mentionLengths` text,
	`mentionIds` text,
	`mentionTypes` text,
	`replySourceId` text,
	`replySourceType` text,
	`primarySortKey` text,
	`secondarySortKey` text,
	`replyMediaExpirationTimestampMs` integer,
	`replySourceTypeV2` text,
	`replyStatus` text,
	`replySnippet` text,
	`replyMessageText` text,
	`replyToUserId` text,
	`replyMediaUrl` text,
	`replyMediaPreviewWidth` text,
	`replyMediaPreviewHeight` text,
	`replyMediaUrlMimeType` text,
	`replyMediaUrlFallback` text,
	`replyCtaId` text,
	`replyCtaTitle` text,
	`replyAttachmentType` text,
	`replyAttachmentId` text,
	`replyAttachmentExtra` text,
	`isForwarded` integer,
	`forwardScore` text,
	`hasQuickReplies` integer,
	`adminMsgCtaId` text,
	`adminMsgCtaTitle` text,
	`adminMsgCtaType` text,
	`cannotUnsendReason` text,
	`textHasLinks` text,
	`viewFlags` text,
	`displayedContentTypes` text,
	`viewedPluginKey` text,
	`viewedPluginContext` text,
	`quickReplyType` text,
	`hotEmojiSize` text,
	`replySourceTimestampMs` integer,
	`ephemeralDurationInSec` text,
	`msUntilExpirationTs` integer,
	`ephemeralExpirationTs` integer,
	`takedownState` text,
	`isCollapsed` integer,
	`subthreadKey` text,
	FOREIGN KEY (`threadKey`) REFERENCES `threads`(`threadKey`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE `participants` (
	`_original` text,
	`threadKey` text NOT NULL,
	`userId` text NOT NULL,
	`readWatermarkTimestampMs` integer,
	`readActionTimestampMs` integer,
	`deliveredWatermarkTimestampMs` integer,
	`lastDeliveredActionTimestampMs` integer,
	`isAdmin` integer,
	PRIMARY KEY(`threadKey`, `userId`),
	FOREIGN KEY (`threadKey`) REFERENCES `threads`(`threadKey`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`userId`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE `reactions` (
	`_original` text,
	`threadKey` text,
	`timestampMs` integer,
	`messageId` text,
	`actorId` text,
	`reaction` text
);
--> statement-breakpoint
CREATE TABLE `threads` (
	`_original` text,
	`threadKey` text PRIMARY KEY NOT NULL,
	`lastReadWatermarkTimestampMs` integer,
	`threadType` text,
	`folderName` text,
	`parentThreadKey` text,
	`lastActivityTimestampMs` integer,
	`snippet` text,
	`threadName` text,
	`threadPictureUrl` text,
	`needsAdminApprovalForNewParticipant` integer,
	`threadPictureUrlFallback` text,
	`threadPictureUrlExpirationTimestampMs` integer,
	`removeWatermarkTimestampMs` integer,
	`muteExpireTimeMs` integer,
	`groupNotificationSettings` text,
	`isAdminSnippet` integer,
	`snippetSenderContactId` text,
	`snippetStringHash` text,
	`snippetStringArgument1` text,
	`snippetAttribution` text,
	`mailboxType` text,
	`draftMessage` text,
	`snippetAttributionStringHash` text,
	`disappearingSettingTtl` integer,
	`disappearingSettingUpdatedTs` integer,
	`disappearingSettingUpdatedBy` text,
	`cannotReplyReason` text,
	`customEmoji` text,
	`customEmojiImageUrl` text,
	`outgoingBubbleColor` text,
	`themeFbid` text,
	`authorityLevel` integer,
	`muteMentionExpireTimeMs` integer,
	`muteCallsExpireTimeMs` integer,
	`ongoingCallState` text,
	`cannotUnsendReason` text,
	`snippetHasEmoji` integer,
	`hasPersistentMenu` integer,
	`disableComposerInput` integer,
	`shouldRoundThreadPicture` integer,
	`proactiveWarningDismissTime` integer,
	`isCustomThreadPicture` integer,
	`otidOfFirstMessage` text,
	`normalizedSearchTerms` text,
	`additionalThreadContext` text,
	`disappearingThreadKey` text,
	`isDisappearingMode` integer,
	`disappearingModeInitiator` text,
	`unreadDisappearingMessageCount` integer,
	`lastMessageCtaId` text,
	`lastMessageCtaType` text,
	`lastMessageCtaTimestampMs` integer,
	`consistentThreadFbid` text,
	`threadDescription` text,
	`unsendLimitMs` integer,
	`capabilities2` text,
	`capabilities3` text,
	`syncGroup` text,
	`threadInvitesEnabled` integer,
	`threadInviteLink` text,
	`isAllUnreadMessageMissedCallXma` integer,
	`lastNonMissedCallXmaMessageTimestampMs` integer,
	`threadInvitesEnabledV2` integer,
	`hasPendingInvitation` integer,
	`eventStartTimestampMs` integer,
	`eventEndTimestampMs` integer,
	`takedownState` text,
	`secondaryParentThreadKey` text,
	`igFolder` text,
	`inviterId` text,
	`threadTags` text,
	`threadStatus` text,
	`threadSubtype` text,
	`pauseThreadTimestamp` integer,
	`nullstateDescriptionText1` text,
	`nullstateDescriptionText2` text,
	`nullstateDescriptionText3` text,
	`nullstateDescriptionType1` text,
	`nullstateDescriptionType2` text,
	`nullstateDescriptionType3` text,
	`viewedPluginKey` text,
	`viewedPluginContext` text,
	`clientThreadKey` text,
	`capabilities` text
);
--> statement-breakpoint
CREATE TABLE `typing_indicators` (
	`_original` text,
	`threadKey` text NOT NULL,
	`minTimestampMs` integer,
	`minMessageId` text,
	`maxTimestampMs` integer,
	`maxMessageId` text,
	`isLoadingBefore` integer,
	`isLoadingAfter` integer,
	`hasMoreBefore` integer,
	`hasMoreAfter` integer
);
--> statement-breakpoint
CREATE TABLE `users` (
	`_original` text,
	`id` text PRIMARY KEY NOT NULL,
	`profilePictureUrl` text,
	`name` text,
	`username` text
);
