{
    "request_id": null,
    "payload": {
      "name": null,
      "step": [
        1,
        [
          1,
          [
            4,
            0,
            1,
            [
              5,
              "mciTraceLog",
              [
                19,
                "600"
              ],
              "MCITraceUnsampledEventTraceId",
              [
                9
              ],
              [
                19,
                "0"
              ],
              [
                9
              ],
              "DatascriptExecute_SyncGroup_ServerTrace:1",
              [
                19,
                "9"
              ]
            ]
          ]
        ],
        [
          1,
          [
            4,
            0,
            1,
            [
              5,
              "executeFirstBlockForSyncTransaction",
              [
                19,
                "1"
              ],
              [
                19,
                "7091436332424459160"
              ],
              "HCwAABaqDxaq0sUdEwUWxIn_-8DOsT8A",
              "HCwAABasDxaq0sUdEwUWxIn_-8DOsT8A",
              [
                19,
                "2"
              ],
              false,
              [
                19,
                "0"
              ],
              false,
              [
                19,
                "1"
              ],
              [
                9
              ]
            ]
          ],
          [
            23,
            [
              2,
              0
            ],
            [
              1,
              [
                1,
                [
                  4,
                  1,
                  1,
                  [
                    5,
                    "checkAuthoritativeMessageExists",
                    [
                      19,
                      "6583971524979566"
                    ],
                    "7091436849629295116"
                  ]
                ],
                [
                  23,
                  [
                    26,
                    [
                      2,
                      1
                    ]
                  ],
                  [
                    1,
                    [
                      1,
                      [
                        5,
                        "verifyThreadExists",
                        [
                          19,
                          "6583971524979566"
                        ],
                        [
                          19,
                          "2"
                        ],
                        "inbox",
                        [
                          19,
                          "0"
                        ],
                        [
                          19,
                          "60"
                        ],
                        [
                          19,
                          "1"
                        ]
                      ]
                    ],
                    [
                      1,
                      [
                        5,
                        "bumpThread",
                        [
                          19,
                          "1690730297691"
                        ],
                        [
                          19,
                          "1"
                        ],
                        [
                          19,
                          "6583971524979566"
                        ]
                      ]
                    ],
                    [
                      1,
                      [
                        5,
                        "moveThreadToInboxAndUpdateParent",
                        [
                          19,
                          "6583971524979566"
                        ],
                        [
                          19,
                          "0"
                        ]
                      ]
                    ],
                    [
                      1,
                      [
                        3,
                        2,
                        [
                          19,
                          "4449570745351127774"
                        ]
                      ]
                    ],
                    [
                      3,
                      3,
                      [
                        19,
                        "4764140727770899461"
                      ]
                    ],
                    [
                      3,
                      4,
                      [
                        19,
                        "72057594725794818"
                      ]
                    ],
                    [
                      5,
                      "writeThreadCapabilities",
                      [
                        19,
                        "6583971524979566"
                      ],
                      [
                        2,
                        2
                      ],
                      [
                        2,
                        3
                      ],
                      [
                        2,
                        4
                      ]
                    ],
                    [
                      1,
                      [
                        5,
                        "updateThreadSnippet",
                        [
                          19,
                          "6583971524979566"
                        ],
                        "You: AHA",
                        false,
                        [
                          19,
                          "17842024422040162"
                        ],
                        false,
                        [
                          9
                        ],
                        [
                          9
                        ],
                        false
                      ]
                    ],
                    [
                      1,
                      [
                        5,
                        "insertMessage",
                        "AHA",
                        [
                          9
                        ],
                        [
                          19,
                          "80"
                        ],
                        [
                          19,
                          "6583971524979566"
                        ],
                        [
                          19,
                          "0"
                        ],
                        [
                          19,
                          "1690730297691"
                        ],
                        [
                          19,
                          "1690730297691"
                        ],
                        [
                          9
                        ],
                        "mid.$gABdkFlP1K26P2KZBW2Jp2D4hRPIM",
                        "7091436849629295116",
                        [
                          19,
                          "17842024422040162"
                        ],
                        [
                          9
                        ],
                        false,
                        [
                          19,
                          "0"
                        ],
                        [
                          19,
                          "0"
                        ],
                        [
                          19,
                          "2"
                        ],
                        [
                          19,
                          "2"
                        ],
                        false,
                        [
                          9
                        ],
                        [
                          9
                        ],
                        [
                          9
                        ],
                        [
                          9
                        ],
                        [
                          9
                        ],
                        [
                          9
                        ],
                        [
                          9
                        ],
                        [
                          9
                        ],
                        [
                          9
                        ],
                        [
                          9
                        ],
                        [
                          9
                        ],
                        [
                          9
                        ],
                        [
                          9
                        ],
                        [
                          9
                        ],
                        [
                          9
                        ],
                        [
                          9
                        ],
                        [
                          9
                        ],
                        [
                          9
                        ],
                        [
                          9
                        ],
                        [
                          9
                        ],
                        [
                          9
                        ],
                        [
                          9
                        ],
                        [
                          9
                        ],
                        [
                          9
                        ],
                        [
                          9
                        ],
                        false,
                        [
                          9
                        ],
                        [
                          9
                        ],
                        [
                          9
                        ],
                        [
                          19,
                          "0"
                        ],
                        false,
                        [
                          19,
                          "0"
                        ],
                        [
                          19,
                          "1"
                        ],
                        [
                          9
                        ],
                        [
                          9
                        ],
                        [
                          19,
                          "0"
                        ],
                        [
                          9
                        ],
                        [
                          9
                        ],
                        [
                          9
                        ],
                        [
                          9
                        ],
                        [
                          9
                        ],
                        false,
                        [
                          9
                        ]
                      ]
                    ],
                    [
                      1,
                      [
                        5,
                        "appendDataTraceAddon",
                        "#wNGo2XQ9RjCiKrXtm/E5iQ",
                        [
                          19,
                          "203"
                        ],
                        [
                          19,
                          "1"
                        ],
                        [
                          9
                        ],
                        "202"
                      ]
                    ],
                    [
                      1,
                      [
                        5,
                        "appendDataTraceAddon",
                        "#wNGo2XQ9RjCiKrXtm/E5iQ",
                        [
                          19,
                          "130"
                        ],
                        [
                          19,
                          "1"
                        ],
                        [
                          9
                        ],
                        "{\"2\":1}"
                      ]
                    ],
                    [
                      1,
                      [
                        5,
                        "updateReadReceipt",
                        [
                          19,
                          "1690730297691"
                        ],
                        [
                          19,
                          "6583971524979566"
                        ],
                        [
                          19,
                          "17842024422040162"
                        ],
                        [
                          19,
                          "0"
                        ]
                      ]
                    ],
                    [
                      1,
                      [
                        5,
                        "setForwardScore",
                        [
                          19,
                          "6583971524979566"
                        ],
                        "mid.$gABdkFlP1K26P2KZBW2Jp2D4hRPIM",
                        [
                          19,
                          "1690730297691"
                        ],
                        [
                          9
                        ]
                      ]
                    ],
                    [
                      1,
                      [
                        5,
                        "setMessageDisplayedContentTypes",
                        [
                          19,
                          "6583971524979566"
                        ],
                        "mid.$gABdkFlP1K26P2KZBW2Jp2D4hRPIM",
                        [
                          19,
                          "1690730297691"
                        ],
                        "AHA",
                        false,
                        false
                      ]
                    ],
                    [
                      1,
                      [
                        5,
                        "updateParticipantLastMessageSendTimestamp",
                        [
                          19,
                          "6583971524979566"
                        ],
                        [
                          19,
                          "17842024422040162"
                        ],
                        [
                          19,
                          "1690730297691"
                        ]
                      ]
                    ]
                  ]
                ],
                [
                  1,
                  [
                    5,
                    "upsertSequenceId",
                    [
                      19,
                      "982"
                    ]
                  ]
                ]
              ]
            ],
            [
              1,
              [
                1,
                [
                  5,
                  "executeFinallyBlockForSyncTransaction",
                  false,
                  [
                    19,
                    "1"
                  ],
                  [
                    19,
                    "7091436332424459160"
                  ]
                ]
              ]
            ],
            [
              1,
              [
                4,
                0,
                1,
                [
                  5,
                  "mciTraceLog",
                  [
                    19,
                    "601"
                  ],
                  "MCITraceUnsampledEventTraceId",
                  [
                    9
                  ],
                  [
                    19,
                    "0"
                  ],
                  [
                    9
                  ],
                  [
                    9
                  ],
                  [
                    19,
                    "9"
                  ]
                ]
              ]
            ]
          ]
        ]
      ]
    },
    "sp": [
      "mciTraceLog",
      "executeFirstBlockForSyncTransaction",
      "checkAuthoritativeMessageExists",
      "verifyThreadExists",
      "bumpThread",
      "moveThreadToInboxAndUpdateParent",
      "writeThreadCapabilities",
      "updateThreadSnippet",
      "insertMessage",
      "appendDataTraceAddon",
      "updateReadReceipt",
      "setForwardScore",
      "setMessageDisplayedContentTypes",
      "updateParticipantLastMessageSendTimestamp",
      "upsertSequenceId",
      "executeFinallyBlockForSyncTransaction"
    ],
    "target": 3
  }
