export const MM_DEFAULT_VALUES = {
  sync_groups: {
    syncStatus: 0,
    sendSyncParams: false,
    minTimeToSyncTimestampMs: 0,
    canIgnoreTimestamp: false,
    priority: 0,
    lastSyncRequestTimestampMs: 0,
    lastSyncCompletedTimestampMs: 0,
    syncChannel: 1,
  },
  pending_tasks: {
    enqueueTimestampMs: 0,
    firstExecutedTimestampMs: 0,
    failureCount: 0,
    minTimeToSyncTimestampMs: 0,
    pluginType: 0,
    priority: 0,
  },
  pending_fire_and_forget_tasks: {
    enqueueTimestampMs: 0,
    priority: 0,
  },
  contacts: {
    isMessengerUser: false,
    isMemorialized: false,
    blockedByViewerStatus: 0,
    rank: 0,
    contactType: 0,
    contactTypeExact: 0,
    canViewerMessage: true,
    gender: 0,
    authorityLevel: 0,
    optimisticBlockedByViewerStatus: 0,
    optimisticBlockedByViewerStatusTimestampMs: 0,
    contactReachabilityStatusType: 0,
    restrictionType: 0,
    waConnectStatus: 0,
    capabilities2: 0,
    isEmployee: false,
  },
  ig_contact_info: { e2eeEligibility: 0 },
  reactions: {
    timestampMs: 0,
    authorityLevel: 0,
  },
  threads: {
    lastActivityTimestampMs: 0,
    lastReadWatermarkTimestampMs: 0,
    removeWatermarkTimestampMs: 0,
    muteExpireTimeMs: 0,
    isAdminSnippet: false,
    ongoingCallState: 0,
    snippetHasEmoji: false,
    hasPersistentMenu: false,
    disableComposerInput: false,
    capabilities: 0,
    isCustomThreadPicture: false,
    isDisappearingMode: false,
    unreadDisappearingMessageCount: 0,
    authorityLevel: 0,
    capabilities2: 0,
    muteCallsExpireTimeMs: 0,
    unsendLimitMs: 0,
    threadInvitesEnabled: 0,
    threadInvitesEnabledV2: 0,
    capabilities3: 0,
    muteMentionExpireTimeMs: 0,
    isReadReceiptsDisabled: false,
    readReceiptsDisabledV2: 0,
    capabilities4: 0,
  },
  threads_ranges_v2__generated: {
    minThreadKey: 0,
    minLastActivityTimestampMs: 0,
    maxThreadKey: 0,
    maxLastActivityTimestampMs: 0,
    isLoadingBefore: false,
    isLoadingAfter: false,
    hasMoreBefore: false,
    hasMoreAfter: false,
  },
  messages: {
    timestampMs: 0,
    primarySortKey: 0,
    secondarySortKey: 0,
    isAdminMessage: false,
    sendStatus: 0,
    sendStatusV2: 0,
    isUnsent: false,
    replyStatus: 0,
    replyAttachmentType: 0,
    hasQuickReplies: false,
    textHasLinks: false,
    viewFlags: 0,
    displayedContentTypes: 1,
    quickReplyType: 0,
    authorityLevel: 0,
    unsentTimestampMs: 0,
    isCollapsed: false,
    messageRenderingType: 0,
  },
  messages_ranges_v2__generated: {
    isLoadingBefore: false,
    isLoadingAfter: false,
    hasMoreBefore: false,
    hasMoreAfter: false,
  },
  participants: {
    readWatermarkTimestampMs: 0,
    deliveredWatermarkTimestampMs: 0,
    authorityLevel: 0,
    readActionTimestampMs: 0,
    groupParticipantJoinState: 0,
    threadRoles: 0,
  },
  attachments: {
    timestampMs: 0,
    attachmentType: 0,
    hasMedia: false,
    isSharable: false,
    hasXma: false,
    attachmentIndex: 0,
    authorityLevel: 0,
  },
  attachments_ranges_v2__generated: {
    mediaGroup: 0,
    isLoadingBefore: false,
    isLoadingAfter: false,
    hasMoreBefore: false,
    hasMoreAfter: false,
  },
  attachment_items: { attachmentIndex: 0 },
  group_membership_approval_requests: { authorityLevel: 0 },
  admin_message_ctas: {
    timestampMs: 0,
    showAdChoiceIcon: false,
  },
  thread_nullstate: {
    ctaType: 0,
    privacyTextCtaType: 0,
  },
  messages_status: { timestampMs: 0 },
  polls: { pollType: 0 },
  poll_options_v2: {
    voteCount: 0,
    sortKeyVotingTimestamp: 0,
    sortKeyCreationTimestamp: 0,
  },
  filtered_threads_ranges_v3__generated: {
    minThreadKey: 0,
    minLastActivityTimestampMs: 0,
    maxThreadKey: 0,
    maxLastActivityTimestampMs: 0,
    isLoadingBefore: false,
    isLoadingAfter: false,
    hasMoreBefore: false,
    hasMoreAfter: false,
    folderName: 'inbox',
    secondaryThreadRangeFilter: 0,
    threadRangeFilterValue: '',
  },
  community_folders: {
    capabilities: 0,
    notificationMutedUntil: 0,
    inviteStatus: 0,
    capabilities2: 0,
    capabilities3: 0,
  },
  community_members: {
    source: 0,
    adminActions: 0,
    contactCapabilities: 0,
    channelBadges: 0,
    threadRoles: 0,
    requestId: '',
  },
  inbox_threads_ranges: {
    minThreadKey: 0,
    minLastActivityTimestampMs: 0,
    isLoadingBefore: false,
    hasMoreBefore: false,
  },
  community_direct_invites_presets: {
    fallbackUrl: '',
    pictureUrlExpirationTimestampMs1: 0,
    pictureUrlExpirationTimestampMs2: 0,
    presetTypeV2: 'ALL_MEMBERS',
  },
  sync_group_threads_ranges: {
    minThreadKey: 0,
    minLastActivityTimestampMs: 0,
    isLoadingBefore: false,
    hasMoreBefore: false,
  },
  community_chat_polls: { pollType: 0 },
  community_chat_poll_options: {
    voteCount: 0,
    sortKeyVotingTimestamp: 0,
    sortKeyCreationTimestamp: 0,
  },
  reactions_v2: {
    viewerReactionTimestampMs: 0,
    lastUpdatedTimestampMs: 0,
  },
  group_invitations_pending: {
    communityJoinRequestStatus: 0,
    communityParticipationControlRequestStatus: 0,
    communityParticipationControlSetting: 0,
  },
  thread_label_mappings: { sortKey: 0 },
  inbox_view_state: { value: '' },
  inbox_view_state_v2: { value: '' },
  discoverable_chat_participants: { source: 0 },
  roll_calls: {
    viewerHasContributed: false,
    viewerCanEditPrompt: false,
    isBlurred: false,
    canViewWithoutContributing: false,
  },
  roll_call_contributions_v2: {
    contributorId: 0,
    contributionSource: 0,
  },
  shared_albums: {
    lastActivityTimestampMs: 0,
    contributionCount: 0,
  },
  shared_album_contributions: {
    creationTimestampMs: 0,
    creatorId: 0,
  },
  search_queries: { surfaceType: 1 },
  universal_search_recent_searches: { lastAccessedTimestampMs: 0 },
  cm_search_nullstate_metadata: { score: 0 },
  contact_upload_settings: { authorityLevel: 0 },
  presence_settings: {
    isActiveStatusViewable: false,
    isActiveStatusViewableOnFb: false,
    isActiveStatusViewableOnMessenger: false,
    hasConvertedToViewSideSettings: false,
  },
  video_chat_links_joining: { canAnonymousUsersJoin: 0 },
  notification_settings: {
    includeInSwitchAccountBadges: false,
    mutePageAccountMessageReminder: false,
  },
  avatar_settings: { enableAvatarHotlike: false },
  messaging_privacy_settings: { readReceiptsDisabled: 0 },
  rtc_call_events: { isProcessed: false },
  transaction_history: { timestampMs: 0 },
  thread_themes: {
    isDeprecated: false,
    iconUrl: '',
    iconUrlFallback: '',
    backgroundUrl: '',
  },
  ranking_scores: {
    score: 0,
    scoreIndex: 0,
  },
  story_buckets: {
    pageNum: 0,
    readState: 0,
  },
  stories: { authorityLevel: 0 },
  story_viewers: {
    interactionType: 1,
    authorityLevel: 0,
  },
  story_reactions: { authorityLevel: 0 },
  story_ad_unit: { shouldShowAdChoice: false },
  story_overlays: { authorityLevel: 0 },
  rooms: { notificationMutedUntilMs: 0 },
  media_staging: { progress: 0 },
  client_messages: {
    textSize: 0,
    sendStatus: 0,
    isHidden: false,
    isTombstoned: false,
    isReplyOnly: false,
    messageContentType: 0,
    messageContentSubtype: 0,
    messageSource: 0,
    messageCreationType: 0,
    messageEphemeralityType: 0,
    replyStatus: 0,
    replyMessageTextSize: 0,
    replyVicinityStatus: 0,
    isForwarded: false,
    isReadonly: false,
    disabledActionsReason: 0,
    shouldPersist: false,
    shouldHideInSnippet: false,
  },
  client_participants: {
    isPending: false,
    capabilities1: 0,
    capabilities2: 0,
    readActionTsMs: 0,
  },
  client_threads: {
    isAdminSnippet: false,
    isHotlikeSnippet: false,
    groupMemberAddMode: 0,
    capabilities1: 0,
    capabilities2: 0,
    isHidden: false,
    isTombstoned: false,
    isPending: false,
    isShadowThread: false,
    pinnedMessagesCount: 0,
  },
  data_trace_meta: {
    initTimestampMs: 0,
    foregroundTimestampMs: 0,
    traceType: 0,
    shouldFlush: false,
  },
  data_trace_addon: { timestampMs: 0 },
  secure_encrypted_backups_client_state: {
    authorityLevel: 0,
    encryptionVersion: 0,
    revisionVersion: 0,
  },
  secure_encrypted_backups_epochs: { authorityLevel: 0 },
  encrypted_backups: {
    authorityLevel: 0,
    hasOtcEligibleDevices: false,
  },
  secure_encrypted_backups_generated_recovery_code: { virtualDeviceType: 1 },
  encrypted_backups_virtual_devices: {
    virtualDeviceType: 1,
    removalStatus: 1,
  },
  encrypted_backups_metadata: { authorityLevel: 0 },
  cutover_threads: {
    isMigrated: false,
    showOpenMessageHistory: false,
  },
  persistent_menu_ctas: { ctaType: 'fallback' },
} as const
