export interface IGThread {
  threadKey: string
  lastReadWatermarkTimestampMs?: number
  authorityLevel?: number
  mailboxType?: number
  threadType?: number
  folderName?: string
  ongoingCallState?: number
  parentThreadKey?: string
  lastActivityTimestampMs?: number
  snippet?: string
  threadName?: string
  threadPictureUrl?: string
  needsAdminApprovalForNewParticipant?: boolean
  threadPictureUrlFallback?: string
  threadPictureUrlExpirationTimestampMs?: number
  removeWatermarkTimestampMs?: number
  muteExpireTimeMs?: number
  muteMentionExpireTimeMs?: number
  muteCallsExpireTimeMs?: number
  groupNotificationSettings?: number
  isAdminSnippet?: boolean
  snippetSenderContactId?: string
  snippetStringHash?: number
  snippetStringArgument1?: string
  snippetAttribution?: string
  snippetAttributionStringHash?: number
  disappearingSettingTtl?: number
  disappearingSettingUpdatedTs?: number
  disappearingSettingUpdatedBy?: string
  cannotReplyReason?: number
  customEmoji?: string
  customEmojiImageUrl?: string
  outgoingBubbleColor?: string
  themeFbid?: string
  nullstateDescriptionText1?: string
  nullstateDescriptionType1?: number
  nullstateDescriptionText2?: string
  nullstateDescriptionType2?: number
  nullstateDescriptionText3?: string
  nullstateDescriptionType3?: number
  draftMessage?: string
  snippetHasEmoji?: boolean
  hasPersistentMenu?: boolean
  disableComposerInput?: boolean
  cannotUnsendReason?: number
  viewedPluginKey?: string
  viewedPluginContext?: string
  clientThreadKey?: string
  capabilities?: number
  shouldRoundThreadPicture?: boolean
  proactiveWarningDismissTime?: number
  isCustomThreadPicture?: boolean
  otidOfFirstMessage?: string
  normalizedSearchTerms?: string
  additionalThreadContext?: string
  disappearingThreadKey?: string
  isDisappearingMode?: boolean
  disappearingModeInitiator?: string
  unreadDisappearingMessageCount?: number
  lastMessageCtaId?: string
  lastMessageCtaType?: number
  lastMessageCtaTimestampMs?: number
  consistentThreadFbid?: string
  threadDescription?: string
  unsendLimitMs?: number
  capabilities2?: number
  capabilities3?: number
  syncGroup?: number
  threadInvitesEnabled?: boolean
  threadInviteLink?: string
  isAllUnreadMessageMissedCallXma?: boolean
  lastNonMissedCallXmaMessageTimestampMs?: number
  threadInvitesEnabledV2?: boolean
  hasPendingInvitation?: boolean
  eventStartTimestampMs?: number
  eventEndTimestampMs?: number
  takedownState?: number
  secondaryParentThreadKey?: string
  igFolder?: string
  inviterId?: string
  threadTags?: string[]
  threadStatus?: number
  threadSubtype?: number
  pauseThreadTimestamp?: number
  avatarStickerInstructionKeyId?: string
  avatarStickerId?: string
  avatarStickerThumbnailImageUrl?: string
  avatarStickerThumbnailImageMimeType?: string
  avatarStickerOriginalImageUrl?: string
  avatarStickerOriginalImageMimeType?: string
  memberCount?: number
}

export interface IGMessage {
  threadKey?: string
  timestampMs?: number
  messageId?: string
  offlineThreadingId?: string
  authorityLevel?: number
  primarySortKey?: string
  senderId?: string
  isAdminMessage?: boolean
  sendStatus?: number
  sendStatusV2?: number
  text?: string
  subscriptErrorMessage?: string
  secondarySortKey?: string
  stickerId?: string
  messageRenderingType?: number
  isUnsent?: boolean
  unsentTimestampMs?: number
  mentionOffsets?: number[]
  mentionLengths?: number[]
  mentionIds?: string[]
  mentionTypes?: number[]
  replySourceId?: string
  replySourceType?: number
  replySourceTypeV2?: number
  replyStatus?: number
  replySnippet?: string
  replyMessageText?: string
  replyToUserId?: string
  replyMediaExpirationTimestampMs?: number
  replyMediaUrl?: string
  replyMediaPreviewWidth?: number
  replyMediaPreviewHeight?: number
  replyMediaUrlMimeType?: string
  replyMediaUrlFallback?: string
  replyCtaId?: string
  replyCtaTitle?: string
  replyAttachmentType?: number
  replyAttachmentId?: string
  replyAttachmentExtra: string
  isForwarded: boolean
  forwardScore: number
  hasQuickReplies: boolean
  adminMsgCtaId: string
  adminMsgCtaTitle: string
  adminMsgCtaType: number
  cannotUnsendReason: number
  textHasLinks: boolean
  viewFlags: number
  displayedContentTypes: number[]
  viewedPluginKey: string
  viewedPluginContext: string
  quickReplyType: number
  hotEmojiSize: number
  replySourceTimestampMs: number
  ephemeralDurationInSec: number
  msUntilExpirationTs: number
  ephemeralExpirationTs: number
  takedownState: number
  isCollapsed: boolean
  subthreadKey: string
}

export interface IGAttachment {
  threadKey: string
  messageId: string
  attachmentFbid: string
  filename: string
  filesize: number
  hasMedia: boolean
  playableUrl: string
  playableUrlFallback: string
  playableUrlExpirationTimestampMs: number
  playableUrlMimeType: string
  dashManifest: string
  previewUrl: string
  previewUrlFallback: string
  previewUrlExpirationTimestampMs: number
  previewUrlMimeType: string
  miniPreview: string
  previewWidth: number
  previewHeight: number
  attributionAppId: string
  attributionAppName: string
  attributionAppIcon: string
  attributionAppIconFallback: string
  attributionAppIconUrlExpirationTimestampMs: number
  localPlayableUrl: string
  playableDurationMs: number
  attachmentIndex: number
  accessibilitySummaryText: string
  isPreviewImage: boolean
  originalFileHash: string
  attachmentType: number
  timestampMs: number
  offlineAttachmentId: string
  hasXma: boolean
  xmaLayoutType: number
  xmasTemplateType: number
  titleText: string
  subtitleText: string
  descriptionText: string
  sourceText: string
  faviconUrlExpirationTimestampMs: number
  isBorderless: boolean
  previewUrlLarge: string
  samplingFrequencyHz: number
  waveformData: string
  authorityLevel: number
}

export interface IGParticipant {
  name: string
  username: string
  userId: string
}
